### ISSUE TITLE
Defender flags SPCB.exe v3.2 as Trojan:Win32/Bluteal.B!rfn

### ISSUE THREAD

**Issue by bdgit** [bramdejager/spcb#83] opened 2018-06-05 13:16 UTC
Today, 6/5/2018, Windows defender flagged and quarantined SPCB.exe v3.2.

as
Trojan:Win32/Bluteal.B!rfn

**Comment by cangot** [comment] 2018-06-05 16:57
I raised a similar issue : [https://github.com/bramdejager/spcb/issues/82](https://github.com/bramdejager/spcb/issues/82)

**Comment by vman** [comment] 2018-06-05 18:41
The information from [this thread](https://social.msdn.microsoft.com/Forums/en-US/31b287ec-24c7-46f5-93e5-65bf8a2f7e93/windows-defender-detecting-visual-studio-dll-file-as-trojanwin32blutealbrfn?forum=msbuild) suggests Windows Defender might be giving a false positive for unsigned dlls/exes.

Checking SPCB.exe, it indeed doesn't have a strong name:
![image](https://user-images.githubusercontent.com/173794/40995598-6031db3e-68f7-11e8-8750-c51910f224cf.png)

**Comment by Benny56** [comment] 2018-06-07 09:59
v3.7 is also flagged

**Comment by bramdejager** [comment] 2018-11-23 08:00
> The information from [this thread](https://social.msdn.microsoft.com/Forums/en-US/31b287ec-24c7-46f5-93e5-65bf8a2f7e93/windows-defender-detecting-visual-studio-dll-file-as-trojanwin32blutealbrfn?forum=msbuild) suggests Windows Defender might be giving a false positive for unsigned dlls/exes.
> 
> Checking SPCB.exe, it indeed doesn't have a strong name:
> 
> ![image](https://user-images.githubusercontent.com/173794/40995598-6031db3e-68f7-11e8-8750-c51910f224cf.png)

There is indeed no strong signing happening. I don't have a proper certificate to perform code signing. Singing it with a self-signed certificate creates other problems and does not solve this. 

I'm curious if this is still an issue at the moment? Can anyone comment?

**Comment by bramdejager** [comment] 2019-04-16 07:46
Received no reply anymore, closing the issue for now.

**Closed by bramdejager** 2019-04-16 07:46 UTC

**Comment by webash** [comment] 2019-04-29 13:15
I can confirm that Windows Defender (ATP, too) is still flagging this application as suspicious, likely due to the lack of DLL/code signing. I was reviewing a recent alert in WD ATP on @vman 's machine (we work together). Let me know if I can provide any information from the alert's that might help stop such false positive flagging in lieu of the expense/effort of code signing.

**Comment by webash** [comment] 2019-08-21 16:06
@bramdejager we're still hitting this occasionally and it briefly gives me a fright until I remember this. If there isn't a solution without a code signing certificate, perhaps sponsorship could solve the funding gap for the cert? :)
